LIBFCREPO-1830. Replace @controller.stub with RSpec mocks
In MiniTest 6, the way arguments have treated has changed, resulting
in errors when running the tests such as:

```
Error:
DownloadUrlsControllerTest#test_should_not_be_able_to_set_token_or_creator_on_create:
TypeError: no implicit conversion of SolrDocument into Hash
    test/controllers/download_urls_controller_test.rb:179:in `stub_find_solr_document'
    test/controllers/download_urls_controller_test.rb:67:in `block in <class:DownloadUrlsControllerTest>'
```

and

```
Error:
DownloadUrlsControllerTest#test_create_download_url_should_respond_with_404_if_document_cannot_be_found:
NoMethodError: undefined method `fetch' for nil:NilClass
    test/controllers/download_urls_controller_test.rb:121:in `block in <class:DownloadUrlsControllerTest>'
```

Fixed by changing @controller.stub to using RSpec mocks, which do
not have the issue.

The "stub_find_solr_document" method in "download_urls_controller_test"
no longer needs to use a block so updated tests as needed.

https://umd-dit.atlassian.net/browse/LIBFCREPO-1830