LIBFCREPO-1830. Updated gems to fix errors running "rails test"
* Updated the “sqlite” dependency, to match stock Rails 8

Fixed the following error:

```
/Users/dsteelma/.rvm/rubies/ruby-3.2.9/lib/ruby/3.2.0/bundler/rubygems_integration.rb:280:in `block (2 levels) in replace_gem': Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (>= 2.1), already activated sqlite3-1.7.3-arm64-darwin. Make sure all dependencies are added to Gemfile. (LoadError)
	from /Users/dsteelma/.rvm/gems/ruby-3.2.9@archelon/gems/activerecord-8.0.5/lib/active_record/connection_adapters/sqlite3_adapter.rb:14:in `<top (required)>'
    ...
```

* Restored "connection_pool" gem constraint, as it is still necessary.

Fixed the following error:

```
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
/Users/dsteelma/.rvm/gems/ruby-3.2.9@archelon/gems/connection_pool-3.0.2/lib/connection_pool.rb:48:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /Users/dsteelma/.rvm/gems/ruby-3.2.9@archelon/gems/react-rails-3.2.1/lib/react/server_rendering.rb:19:in `new'
	from /Users/dsteelma/.rvm/gems/ruby-3.2.9@archelon/gems/react-rails-3.2.1/lib/react/server_rendering.rb:19:in `reset_pool'
    ...
```

* Updated the “react-rails” dependency to 3.3.1

Fixed the following error:

```
/Users/dsteelma/.rvm/gems/ruby-3.2.9@archelon/gems/react-rails-3.2.1/lib/react/rails/railtie.rb:81:in `block in <class:Railtie>': undefined method `version' for #<Propshaft::Assembly:0x000000010f1ee618 @config=#<ActiveSupport::OrderedOptions {:paths=>[#<Pathname:/Users/dsteelma/git/umd-fcrepo/archelon/node_modules/bootstrap-icons/font>], :excluded_paths=>[], :version=>"1.0", :prefix=>"/assets", :quiet=>false, :compilers=>[["text/css", Propshaft::Compiler::CssAssetUrls], ["text/css", Propshaft::Compiler::SourceMappingUrls], ["text/javascript", Propshaft::Compiler::JsAssetUrls], ["text/javascript", Propshaft::Compiler::SourceMappingUrls]], :sweep_cache=>false, :server=>true, :relative_url_root=>nil, :precompile=>["server_rendering.js"], :debug=>nil, :compile=>nil, :css_compressor=>nil, :js_compressor=>nil, :unknown_asset_fallback=>false}>> (NoMethodError)

          sprockets_env.version = [sprockets_env.version, "react-#{asset_variant.react_build}"].compact.join("-")
                                                ^^^^^^^^
	from /Users/dsteelma/.rvm/gems/ruby-3.2.9@archelon/gems/railties-8.0.5/lib/rails/initializable.rb:32:in `instance_exec'
    ...
```
https://umd-dit.atlassian.net/browse/LIBFCREPO-1830